src/beans/User.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private int stop_id;
    private String account;
    private String userName;
    private String password;
    private String text;
    private int officeName;
    private int position;
    private Date createdDate;
    private Date updatedDate;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return user_id;
	}
	public void setUserId(int user_id) {
		this.user_id = user_id;
	}
	public int getStopId() {
		return stop_id;
	}
	public void setStopId(int stop_id) {
		this.stop_id = stop_id;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public int getOfficeName() {
		return officeName;
	}
	public void setOfficeName(int officeName) {
		this.officeName = officeName;
	}
	public int getPosition() {
		return position;
	}
	public void setPosition(int position) {
		this.position = position;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}

src/controller/EditServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.UserService;

@WebServlet(urlPatterns = { "/edit" })
public class EditServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        User user = (User) request.getSession().getAttribute("loginUser");

        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();

        if(user == null) {
    		session.setAttribute("errorMessages", messages);
   		 	messages.add("ログインしてください。");
   		 	response.sendRedirect("login");
        }else {
        	int position = user.getPosition();
        	if(position == 1) {
        		request.getRequestDispatcher("/edit.jsp").forward(request, response);
        	}else {
        		session.setAttribute("errorMessages", messages);
   		 		messages.add("閲覧権限がありません。");
   		 		response.sendRedirect("./");
        	}
    	}
    }

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User editUser = getEditUser(request);

		if (isValid(request, messages) == true) {

			try {

				String password = request.getParameter("password");
				UserService userService = new UserService();
			    User thisUser = userService.getUser(editUser.getId());

				if (StringUtils.isEmpty(password)) {
					password = thisUser.getPassword();
					editUser.setPassword(password);
					new UserService().passUpdate(editUser);
				} else {
					editUser.setPassword(password);
					new UserService().update(editUser);
				}
			} catch (NoRowsUpdatedRuntimeException e) {
				messages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
				session.setAttribute("errorMessages", messages);
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("/edit.jsp").forward(request, response);
				return;
			}
			session.setAttribute("editUser", editUser);
			response.sendRedirect("settings");
		} else {
            String userName = request.getParameter("userName");
        	String account = request.getParameter("account");
            String password = request.getParameter("password");

			session.setAttribute("errorMessages", messages);
            request.setAttribute("errorUserName", userName);
            request.setAttribute("errorAccount", account);
            request.setAttribute("errorPassword", password);
			request.setAttribute("editUser", editUser);
			request.getRequestDispatcher("/edit.jsp").forward(request, response);
		}
	}

	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setUserName(request.getParameter("userName"));
		editUser.setAccount(request.getParameter("account"));
		editUser.setOfficeName(Integer.parseInt(request.getParameter("officeName")));
		editUser.setPosition(Integer.parseInt(request.getParameter("position")));
		return editUser;
		}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String userName = request.getParameter("userName");
		String account = request.getParameter("account");
		String officeName = request.getParameter("officeName");
		String position = request.getParameter("position");
		String password = request.getParameter("password");
		String password2 = request.getParameter("password2");
		int id = Integer.parseInt(request.getParameter("id"));


		UserService userService = new UserService();
	    User user = userService.getUser(account);

	    User thisUser = userService.getUser(id);
	    String originalAccount = thisUser.getAccount();

        if (user != null && (!(StringUtils.equals (account, originalAccount)))) {
        	messages.add("このログインIDは既に使用されています。");
		}
		if (StringUtils.isEmpty(account) == true) {
			messages.add("ログインIDを入力してください。");
		}else if (!(account.matches("^[0-9a-zA-Z]+$"))) {
            messages.add("ログインIDは半角英数字で入力してください。");
            //IDは半角英数字に限る。
        }else if (StringUtils.length(account) < 6 || StringUtils.length(account) > 20 ) {
            messages.add("ログインIDは6～20文字で入力してください。");
        }
        if (!(StringUtils.isEmpty(password)) && StringUtils.length(password) < 6 || StringUtils.length(password) > 20 ) {
            messages.add("パスワードは6～20文字で入力してください。");
            //半角6～20文字
        }
		if (StringUtils.equals(password, password2) == false) {
			messages.add("入力したパスワードと確認用パスワードが一致しません。");
		}
		if (StringUtils.isEmpty(userName) == true) {
			messages.add("ユーザー名を入力してください");
		}else if (StringUtils.length(userName) >= 10 ) {
            messages.add("ユーザー名は10文字以内で入力してください。");
        }
		if ((StringUtils.equals(officeName, "1")) && (StringUtils.equals(position, "3"))) {
        	messages.add("支店と部署・役職の組み合わせが不正です。");
        }else if ((StringUtils.equals(officeName, "1")) && (StringUtils.equals(position, "4"))) {
        	messages.add("支店と部署・役職の組み合わせが不正です。");
        }else if(!(StringUtils.equals(officeName, "1")) && (StringUtils.equals(position, "1"))) {
        	messages.add("支店と部署・役職の組み合わせが不正です。");
        }else if(!(StringUtils.equals(officeName, "1")) && (StringUtils.equals(position, "2"))) {
        	messages.add("支店と部署・役職の組み合わせが不正です。");
        }
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.User;
import beans.UserComment;
import beans.UserMessage;
import service.CommentService;
import service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        User user = (User) request.getSession().getAttribute("loginUser");

        boolean isShowMessageForm;
        if (user != null) {
            isShowMessageForm = true;

        } else {
            isShowMessageForm = false;
        }

        List<UserMessage> messages = new MessageService().getMessage((request.getParameter("search")),(request.getParameter("date")),(request.getParameter("last_date")));


        request.setAttribute("loginUser", user);
        request.setAttribute("messages", messages);
        request.setAttribute("isShowMessageForm", isShowMessageForm);

        List<UserComment> comments = new CommentService().getComment();

        boolean isShowCommentForm;
        if (comments != null) {
            isShowCommentForm = true;
        } else {
            isShowCommentForm = false;
        }

        request.setAttribute("userComment", comments);
        request.setAttribute("isShowCommentForm", isShowCommentForm);

        request.getRequestDispatcher("/home.jsp").forward(request, response);
    }

}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login"})
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	 HttpSession session = request.getSession();
         String account = request.getParameter("account");
         String password = request.getParameter("password");

         LoginService loginService = new LoginService();
         User user = loginService.login(account, password);

         if(user != null) {
        	 int stopId = user.getStopId();
         		if(stopId != 1) {
         			session.setAttribute("loginUser", user);
         			response.sendRedirect("./");
         		}else {
         			List<String> message = new ArrayList<String>();
	                message.add("ログインIDまたはパスワードが誤っています。");
	                session.setAttribute("errorMessages", message);
	                response.sendRedirect("login.jsp");
         		}
        }else if(StringUtils.isEmpty(account) || StringUtils.isEmpty(password)){
 			List<String> message = new ArrayList<String>();
            message.add("ログインIDまたはパスワードが入力されていません。");
            session.setAttribute("errorMessages", message);
            response.sendRedirect("login.jsp");
        }else {
            List<String> message = new ArrayList<String>();
            message.add("ログインIDまたはパスワードが誤っています。");
            session.setAttribute("errorMessages", message);
            request.setAttribute("errorAccount", account);
            request.setAttribute("errorPassword", password);
            request.getRequestDispatcher("login.jsp").forward(request, response);
        }
    }
}

src/controller/NewPostServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Message;
import beans.User;
import service.MessageService;

@WebServlet(urlPatterns = { "/newpost" })
public class NewPostServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        User user = (User) request.getSession().getAttribute("loginUser");

        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();

        if(user == null) {
    		session.setAttribute("errorMessages", messages);
   		 	messages.add("ログインしてください。");
   		 	response.sendRedirect("login");
        }else {
        	request.setAttribute("loginUser", user);
        	request.getRequestDispatcher("/newpost.jsp").forward(request, response);
        }
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        HttpSession session = request.getSession();

        List<String> messages = new ArrayList<String>();

        if (isValid(request, messages) == true) {

            User user = (User) session.getAttribute("loginUser");

            Message message = new Message();
            message.setTitle(request.getParameter("title"));
            message.setText(request.getParameter("text"));
            message.setCategory(request.getParameter("category"));
            message.setUserId(user.getId());

            new MessageService().register(message);

            response.sendRedirect("./");
        } else {
            String text = request.getParameter("text");
            String title = request.getParameter("title");
            String category = request.getParameter("category");

            session.setAttribute("errorMessages", messages);
            request.setAttribute("errorTitle", title);
            request.setAttribute("errorText", text);
            request.setAttribute("errorCategory", category);

            request.getRequestDispatcher("newpost.jsp").forward(request, response);
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String text = request.getParameter("text");
        String title = request.getParameter("title");
        String category = request.getParameter("category");

        if (StringUtils.isEmpty(text) == true) {
            messages.add("本文を入力してください。");
        }else if (1000 < text.length()) {
            messages.add("本文は1000文字以下で入力してください。");
        }
        if (StringUtils.isEmpty(title) == true) {
            messages.add("件名を入力してください。");
        }else if (30 < title.length()) {
            messages.add("件名は30文字以下で入力してください。");
        }
        if (StringUtils.isEmpty(category) == true) {
            messages.add("カテゴリを入力してください。");
        }else if (10 < category.length()) {
            messages.add("カテゴリは10文字以下で入力してください。");
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

src/controller/SettingsServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.UserService;


@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	List<User> users = new UserService().getUser();
        request.setAttribute("users", users);

        User user = (User) request.getSession().getAttribute("loginUser");

        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();

        if(user == null) {
    		session.setAttribute("errorMessages", messages);
   		 	messages.add("ログインしてください。");
   		 	response.sendRedirect("login");
        }else {
        	int position = user.getPosition();
        	if(position == 1) {
        		request.getRequestDispatcher("/settings.jsp").forward(request, response);
        	}else {
        		session.setAttribute("errorMessages", messages);
   		 		messages.add("閲覧権限がありません。");
   		 		response.sendRedirect("./");
        	}
    	}
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    		int id = Integer.parseInt(request.getParameter("id"));
    		UserService userService = new UserService();
    		User user = userService.getUser(id);
    		HttpSession session = request.getSession();
    		session.setAttribute("editUser", user);

    		request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

}

WebContent/Edit.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${editUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">

        <script>
		function clickEvent() {
			alert("閲覧権限がありません");
		}
		</script>

    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

         <div class="header">
         	<c:if test="${ empty loginUser }">
				<a href="login">ログイン</a>
			</c:if>
			<c:if test="${ not empty loginUser }">
				<a href="./">ホーム</a>
				<a href="newpost">新規投稿</a>
				<c:choose>
				<c:when test="${ loginUser.position == 1 && loginUser.officeName == 1 }" >
				<a href="settings">ユーザー管理</a>
				</c:when>
				<c:when test="${ loginUser.position != 1 || loginUser.officeName != 1 }" >
				<a href="./" onclick="clickEvent()">ユーザー管理</a>
				</c:when>
				</c:choose>
				<a href="logout">ログアウト</a>
			</c:if>
		</div>

		<c:if test="${loginUser.position == 1}">
            <form action="edit" method="post">
            	<br /> <label>【ユーザー編集】</label> <br /><br />
                <input name="id" value="${editUser.id}" id="id" type="hidden"/>

                <label for="account">ログインID</label>
                <input name="account" value="${editUser.account}" /> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password"id="password"/> <br />

               	<label for="password2">パスワード【確認用】</label>
                <input name="password2"  type="password" id="password2"/> <br />

                <label for="userName">ユーザー名</label>
                <input name="userName" value="${editUser.userName}" id ="name"/> <br />

                <label for="officeName">支店名</label>
			    <c:choose>
					<c:when test="${editUser.officeName == '1' }" >
						<c:out value="001:本社" />
					</c:when>
					<c:when test="${editUser.officeName == '2' }" >
						<c:out value="002:支店A" />
					</c:when>
					<c:when test="${editUser.officeName == '3' }" >
						<c:out value="003:支店B" />
					</c:when>
					<c:when test="${editUser.officeName == '4' }" >
						<c:out value="004:支店C" />
					</c:when>
				</c:choose>
				<select name="officeName">
                <option value="${editUser.officeName}">変更しない</option>
                <option value="1">001:本社</option>
                <option value="2">002:支店A</option>
                <option value="3">003:支店B</option>
                <option value="4">004:支店C</option>
                </select> <br /> <br />


                <label for="officeName">部署・役職</label>
                <c:choose>
					<c:when test="${editUser.position == '1' }" >
						<c:out value="01:総務人事" />
					</c:when>
					<c:when test="${editUser.position == '2' }" >
						<c:out value="02:情報管理" />
					</c:when>
					<c:when test="${editUser.position == '3' }" >
						<c:out value="03:支店長" />
					</c:when>
					<c:when test="${editUser.position == '4' }" >
						<c:out value="04:社員" />
					</c:when>
				</c:choose>
				<select name="position">
                <option value="${editUser.position}">変更しない</option>
                <option value="1">01:総務人事</option>
                <option value="2">02:情報管理</option>
                <option value="3">03:支店長</option>
                <option value="4">04:社員</option>
                </select> <br /><br />

                <input type="submit" value="登録" /> <br />
                <a href="settings">戻る</a>
            </form>
        </c:if>
        <c:if test="${loginUser.position != 1}">
            <font color="red">
			<c:out value="閲覧権限がありません" />
			</font>
		</c:if>
			<div class="copylight"> Copyright(c)ShinchiKasumi</div>
        </div>
    </body>
</html>

WebContent/home.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>【HOME】</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">

		<script>
		function clickEvent() {
			alert("閲覧権限がありません");
		}
		</script>

	</head>
	<body>
		<div class="main-contents">
			<c:if test="${ not empty errorComments }">
                <div class="errorComments">
                    <ul>
                        <c:forEach items="${errorComments}" var="comment">
                            <li><c:out value="${comment}" />
                        </c:forEach>
                    </ul>
	                </div>
                <c:remove var="errorComments" scope="session" />
            </c:if>
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                     <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                	</ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

			<div class="header">
				<c:if test="${ empty loginUser }">
					<a href="login">ログイン</a>してください
					<h3>はなまる掲示板</h3>
				</c:if>

				<c:if test="${ not empty loginUser }">
					<a href="./">ホーム</a>
					<a href="newpost">新規投稿</a>
					<c:choose>
					<c:when test="${ loginUser.position == 1 && loginUser.officeName == 1 }" >
					<a href="settings">管理者画面</a>
					</c:when>
					<c:when test="${ loginUser.position != 1 || loginUser.officeName != 1  }" >
					<a href="./" onclick="clickEvent()">管理者画面</a>
					</c:when>
					</c:choose>
					<a href="logout">ログアウト</a>
				    <br /><br />

					<!-- <form action="" method=""> -->
					【表示絞込み】<br />
					<form action="./" method="get">
					カテゴリー<input type="search" name ="search" list="list"><br />
					投稿日<input type="date" autocomplete="on" name ="date" list="list"> ～ <input type="date" autocomplete="on" name ="last_date" list="list"><br />
					<input type="submit" value="検索">
					</form>
					<br /><br />
				</c:if>
			</div>

			<c:if test="${ not empty loginUser }">
			    <div class="profile">
			        <div class="userName"><h2><c:out value="${loginUser.userName}" /></h2></div>
			        <div class="loginUser">
			            @<c:out value="${loginUser.account}" />
			        </div>
			        <div class="text">
			            <c:out value="${loginUser.text}" />
			        </div>
			    </div>
            <br />

			<div class="messages">
			 <c:forEach items="${messages}" var="message">
			    	<c:if test="${message.isDelete == 0}">
			            <div class="message">
			                <div class="id" style="float:left;"><c:out value="${message.id}:" /></div>
			                <div class="title">【件名】<c:out value="${message.title}" /></div>
			                <div class="date"><fmt:formatDate value="${message.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			                <div class="userName">
			                	<span class="name"><c:out value="${message.userName}" /></span>
			                    <span class="account">@<c:out value="${message.account}" /></span>
			                </div>
			                <div class="text">【本文】<c:out value="${message.text}" /></div>
			                <div class="category">【カテゴリー】<c:out value="${message.category}" /></div>
						</div><br />
				        	<c:if test="${message.userId == loginUser.id}">
				        		<form action="messagedelete" method="post">
				        			<input name="isDelete" value="1" id="is_delete" type="hidden"/>
 									<input name="id" value="${message.id}" id="id" type="hidden"/>
				        			<input type="submit" value="削除"><br /><br />
								</form>
							</c:if>

			<div class="comments">
 				<c:if test="${ isShowCommentForm }">
					<c:forEach items="${userComment}" var="comment">
						<c:if test="${message.id == comment.messageId}">
							<c:if test="${comment.isDelete == 0}">
			            		<div class="comment">
			                		<span class="name">From:<c:out value="${comment.userName}" /></span>
			                   		<span class="account">@<c:out value="${comment.account}" /></span>
			                		<input name="id" value="${comment.messageId}" id="id" type="hidden"/>
			                		<div class="date"><fmt:formatDate value="${comment.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			                		<div class="comment">【コメント】<c:out value="${comment.comment}" /></div>
				        		</div><br />
				        		<c:if test="${comment.userId == loginUser.id}">
				        			<form action="delete" method="post">
				        				<input name="isDelete" value="1" id="is_delete" type="hidden"/>
 										<input name="id" value="${comment.id}" id="id" type="hidden"/>
				        				<input type="submit" value="削除"><br /><br />
									</form>
								</c:if>
				        	</c:if>
						</c:if>
					</c:forEach>
 				</c:if>

					<c:if test="${ isShowMessageForm }">
				        <form action="comment" method="post">
					        <br />コメント（500文字以下）<br />
							<textarea name="comment" cols="100" rows="5" class="tweet-box" ></textarea><br />
							<input name="message_id" value="${message.id}" id="id" type="hidden"/>
							<input name="id" value="${loginUser.id}" id="id" type="hidden"/>
							<input type="submit" value="コメント" >
						</form>
					</c:if>
					<br />
				  <HR WIDTH="n" SIZE="3" color="pink" noshade>
				  <br /><br /></div>
				</c:if>
			   </c:forEach>
			</div></c:if><br />
		<div class="copylight"> Copyright(c)ShinchiKasumi</div>
	</div>
	</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>はなまる掲示板</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>

			<form action="login" method="post"><br />
				<label>【ログイン画面】</label><br />

				<br /><label for="account">ログインID</label>
				<input  name="account" id="account" value = "${errorAccount}"/><br />

				<label for="password">パスワード</label>
				<input name="password" type="password" id="password"/><br />

				<br /><input type="submit" value="ログイン" /> <br />
				<a href="./">戻る</a>
				<br />
			</form>
			<div class="copylight"> Copyright(c)ShinchiKasumi</div>
		</div>
	</body>
</html>